version: "3.9" # optional since v1.27.0
services:
  mtail:
    build: .
    ports:
      - "3903:3903"
    volumes:
      - ./mtail:/etc/mtail
      - logvolume01:/var/log/mtail-nginx
    command:
      [
        "--progs=/etc/mtail",
        "--logs=/var/log/mtail-nginx/access.log",
        "--logs=/var/log/mtail-nginx/error.log",
        "-logtostderr",
      ]
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - logvolume01:/var/log/mtail-nginx
volumes:
  logvolume01: {}
